### ISSUE TITLE
V9 Update Would Be Appreciated

### ISSUE THREAD

**Issue by PhluXx1** [Mr-Byte/pull-players-to-scene#1]
Any plans for a V9 update and if so when? This module is amazing and makes my life a lot easier with all of the scenes I have on the go.

**Comment by Mr-Byte** [comment]
Hi there!

Sorry that I haven't gotten around to marking this as V9 compatible. I just tried it on a copy of V9 and pulling players to a scene using the scene navigation bar works. One thing I've noticed is that pulling players to a scene from the scene directory doesn't work. I'm not sure if this is a V9 issue or was an existing bug.

I'd say for now if you're fine pulling players into a scene using the scene navigation bar, that this is safe to use with V9. In the interim I will try to get a fix for the bug I discovered while testing and publish a new version and will mark that version as being compatible.

**Comment by Mr-Byte** [comment]
Alright, v1.1.1 is marked as V9 compatible and fixes the bug I had found. Enjoy!
