### ISSUE TITLE
Does it work with Foundry V11 ?

### ISSUE THREAD

**Issue by uniwars** [Mr-Byte/pull-players-to-scene#2]
Hi, I used a script to see compatibility checks for all the modules I use before updating to V11 and it returned that this module is not compatible with v11. Is it a compatibility update issue or is the module broken in v11 ? Thank you.

**Comment by Mr-Byte** [comment]
Sorry for the long response! Got a bit busy and hadn't checked on GitHub.

I just verified that this module works on V11. It should be good to go!
